---
- name: Install apache on Debian distributions
  block:
  - name: Install Apache
    apt:
      name: apache2
      update_cache: true
      state: latest

  - name: Start Apache
    service:
      name: apache2
      state: started

  - name: Enable Apache
    service: 
      name: apache2
      enabled: yes
  when: ansible_facts['os_family'] == "Debian"


- name: Install apache on RedHat distributions
  block:
  - name: Install Apache on RedHat
    yum:
      name: httpd
      update_cache: true
      state: latest

  - name: Start Apache on RedHat
    service:
      name: httpd
      state: started

  - name: Enable Apache on RedHat
    service: 
      name: httpd
      enabled: yes
  when: ansible_facts['os_family'] == "RedHat"
