---
- name: Restart Apache on Debian OS
  service: 
    name: apache2
    state: reload
  when: ansible_facts['os_family'] == "Debian"

- name: Restart Apache on Debian OS
  service: 
    name: httpd
    state: reload
  when: ansible_facts['os_family'] == "RedHat"
